# syntax=docker/dockerfile:1

## Build
FROM golang:1.20-bullseye AS build

WORKDIR /app

COPY go.mod ./
COPY go.sum ./
RUN go mod download

COPY *.go ./

RUN go build -o /docker-gs-ping

## Deploy
FROM gcr.io/distroless/base-debian11

WORKDIR /

COPY --from=build /docker-gs-ping /docker-gs-ping

EXPOSE 80

USER nonroot:nonroot

ENTRYPOINT ["/docker-gs-ping"]
